# hello2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2
  namespace: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      imagePullSecrets:
        - name: regcred
      containers:     
      - name: hello2
        image: docker.io/chumpol01/hello2-app:latest  # Replace with the correct image path
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-2:6379"  # Updated to use redis-2 service
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: REDIS_DB
          value: "0"