apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis-1"  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-1-pvc
  namespace: hello-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi